name: build

on: [push]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.101

      - name: Build & Test
        run: make test config=Release

      - name: Upload Nuget
        uses: actions/upload-artifact@v1
        with:
          name: MagnusOpera.Lollipops.0.0.0.nupkg
          path: .nugets

  publish:
    if: contains(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.101

      - name: Build
        run: make nuget config=Release version=${GITHUB_REF#refs/tags/}

      - name: publish nuget
        run: make publish nugetkey=${{secrets.NUGET_KEY}} version=${GITHUB_REF#refs/tags/}
